Repository AY1920S1-CS2113T-F10-1/main, pull requests merged in 2019-10, with the labels that each got.

#57 B-Reminder
  src/main/java/duke/Duke.java
  src/main/java/duke/command/AddCommand.java
  src/main/java/duke/command/ByeCommand.java
  src/main/java/duke/command/Command.java
  src/main/java/duke/command/DeleteCommand.java
  src/main/java/duke/command/DoneCommand.java
  src/main/java/duke/command/FindCommand.java
  src/main/java/duke/command/ListCommand.java
  src/main/java/duke/command/RescheduleCommand.java
  src/main/java/duke/command/ScheduleCommand.java
  src/main/java/duke/exceptions/DukeTimeIntervalTooCloseException.java
  src/main/java/duke/tasks/Task.java
  src/main/java/duke/util/Reminder.java
  src/main/java/duke/util/TimeInterval.java
  src/main/java/duke/util/TimePeriod.java
  src/main/java/duke/util/Ui.java
Labels: status.Ongoing

#67 Added Requests, NUSMods Api and Gson library support
  build.gradle
  src/main/java/duke/util/RequestsData.java
  src/main/java/duke/util/Storage.java
Labels: status.Ongoing

#68 Added JUnit testing for Schedule
  src/test/java/duke/command/ScheduleTest.java
  src/test/java/duke/tasks/TasksTest.java
Labels: status.Ongoing

#70 Clean up code and implement TimePeriod for all tasks except Recurring and FixedDuration
  src/main/java/duke/command/AddCommand.java
  src/main/java/duke/command/RescheduleCommand.java
  src/main/java/duke/command/ScheduleCommand.java
  src/main/java/duke/tasks/Deadline.java
  src/main/java/duke/tasks/DoWithin.java
  src/main/java/duke/tasks/Events.java
  src/main/java/duke/tasks/FixedDurationTasks.java
  src/main/java/duke/tasks/RecurringTask.java
  src/main/java/duke/tasks/Task.java
  src/main/java/duke/tasks/Todo.java
  src/main/java/duke/util/Storage.java
  src/main/java/duke/util/TaskList.java
  src/main/java/duke/util/TimeInterval.java
  src/main/java/duke/util/TimePeriod.java
  src/test/java/duke/tasks/TasksTest.java
Labels: status.Ongoing, type.Enhancement

#72 Added functional API JSON fetching, and module summary class
  .travis.yml
  src/main/java/duke/Duke.java
  src/main/java/duke/command/AddCommand.java
  src/main/java/duke/command/Command.java
  src/main/java/duke/command/DeleteCommand.java
  src/main/java/duke/command/DoneCommand.java
  src/main/java/duke/command/FindCommand.java
  src/main/java/duke/command/ListCommand.java
  src/main/java/duke/command/RescheduleCommand.java
  src/main/java/duke/command/ScheduleCommand.java
  src/main/java/duke/exceptions/ModBadRequestStatus.java
  src/main/java/duke/exceptions/ModCommandException.java
  src/main/java/duke/exceptions/ModEmptyCommandException.java
  src/main/java/duke/exceptions/ModEmptyListException.java
  src/main/java/duke/exceptions/ModException.java
  src/main/java/duke/exceptions/ModInvalidIndexException.java
  src/main/java/duke/exceptions/ModInvalidTimeException.java
  src/main/java/duke/exceptions/ModInvalidTimePeriodException.java
  src/main/java/duke/exceptions/ModMissingArgumentException.java
  src/main/java/duke/exceptions/ModMultipleValuesForSameArgumentException.java
  src/main/java/duke/exceptions/ModNoTimeException.java
  src/main/java/duke/exceptions/ModScheduleException.java
  src/main/java/duke/exceptions/ModTimeIntervalTooCloseException.java
  src/main/java/duke/modules/Deadline.java
  src/main/java/duke/modules/DoWithin.java
  src/main/java/duke/modules/Events.java
  src/main/java/duke/modules/FixedDurationTasks.java
  src/main/java/duke/modules/ModuleInfoSummary.java
  src/main/java/duke/modules/RecurringTask.java
  src/main/java/duke/modules/Task.java
  src/main/java/duke/modules/Todo.java
  src/main/java/duke/util/DateTimeParser.java
  src/main/java/duke/util/DukeParser.java
  src/main/java/duke/util/JsonWrapper.java
  src/main/java/duke/util/NattyWrapper.java
  src/main/java/duke/util/ParserWrapper.java
  src/main/java/duke/util/Reminder.java
  src/main/java/duke/util/RequestsData.java
  src/main/java/duke/util/Storage.java
  src/main/java/duke/util/TaskList.java
  src/main/java/duke/util/TimePeriod.java
  src/main/java/duke/util/Ui.java
  src/test/java/duke/DukeTest.java
  src/test/java/duke/command/ScheduleTest.java
  src/test/java/duke/modules/TasksTest.java
  src/test/java/duke/util/DukeParserTest.java
  src/test/java/duke/util/NattyTesting.java
Labels: status.Ongoing, type.Task

#78 Fixed reminder bug, refractored modules/tasks, refractored some commands and added intitial implementation of CCAUtils
  build.gradle
  src/main/java/duke/Duke.java
  src/main/java/duke/command/AddCommand.java
  src/main/java/duke/command/ByeCommand.java
  src/main/java/duke/command/ScheduleCommand.java
  src/main/java/duke/modules/Deadline.java
  src/main/java/duke/modules/DoWithin.java
  src/main/java/duke/modules/Events.java
  src/main/java/duke/modules/FixedDurationTaskWithIntervalNotBeingUsed.java
  src/main/java/duke/modules/FixedDurationTasks.java
  src/main/java/duke/modules/RecurringTask.java
  src/main/java/duke/modules/RecurringTaskWithIntervalNotBeingUsed.java
  src/main/java/duke/modules/Task.java
  src/main/java/duke/modules/TaskWithInterval.java
  src/main/java/duke/modules/TaskWithPeriod.java
  src/main/java/duke/modules/TaskWithoutTime.java
  src/main/java/duke/modules/Todo.java
  src/main/java/duke/util/Argparse4jParser.java
  src/main/java/duke/util/CcaUtils.java
  src/main/java/duke/util/Reminder.java
  src/main/java/duke/util/TimeInterval.java
  src/main/java/duke/util/TimePeriod.java
  src/test/java/duke/modules/TasksTest.java
Labels: priority.High, severity.High, status.Completed, type.Enhancement, type.Fix, type.Story, type.Task

#96 Report Command to show the report of the modules added
  src/main/java/duke/command/ReportCommand.java
  src/main/java/duke/command/logic/CoreModuleReportCommand.java
  src/main/java/duke/command/logic/GeneralModuleReportCommand.java
  src/main/java/duke/command/logic/UnrestrictedModuleReportCommand.java
  src/main/java/duke/modules/data/Attributes.java
  src/main/java/duke/util/ParserWrapper.java
  src/main/java/duke/util/PlannerUi.java
  src/main/java/duke/util/Ui.java
Labels: type.Feature

#95 SortCommand added to sort the modules in ascending order of the module codes.
  src/main/java/duke/command/PrintTimetable.java
  src/main/java/duke/command/logic/SortCommand.java
  src/main/java/duke/modules/Timetable.java
  src/main/java/duke/modules/data/ModuleTask.java
  src/main/java/duke/util/DukeParser.java
  src/main/java/duke/util/ParserWrapper.java
  src/main/java/duke/util/PlannerUi.java
Labels: type.Feature

#101 [Fix] Suppressed all unchecked casting warnings
  src/main/java/duke/modules/TaskWithMultiplePeriods.java
  src/main/java/duke/util/argparse4j/action/Join.java
Labels: status.Completed, type.Fix

#100 [Not PR-ing to master] Argparse4j simplified but breaks ParserWrapper
  build.gradle
  src/main/java/duke/Duke.java
  src/main/java/duke/GuiLauncher.java
  src/main/java/duke/command/logic/AddCcaCommand.java
  src/main/java/duke/command/logic/AddCcaScheduleCommand.java
  src/main/java/duke/command/logic/Arguments.java
  src/main/java/duke/command/logic/ClearCommand.java
  src/main/java/duke/command/logic/CoreModuleReportCommand.java
  src/main/java/duke/command/logic/EndCommand.java
  src/main/java/duke/command/logic/GeneralModuleReportCommand.java
  src/main/java/duke/command/logic/ModuleCommand.java
  src/main/java/duke/command/logic/RemoveCcaCommand.java
  src/main/java/duke/command/logic/RemoveCommand.java
  src/main/java/duke/command/logic/RemoveModCommand.java
  src/main/java/duke/command/logic/SearchThenAddCommand.java
  src/main/java/duke/command/logic/ShowCcaCommand.java
  src/main/java/duke/command/logic/ShowCommand.java
  src/main/java/duke/command/logic/ShowModuleCommand.java
  src/main/java/duke/command/logic/SortCommand.java
  src/main/java/duke/command/logic/UnrestrictedModuleReportCommand.java
  src/main/java/duke/gui/DialogBox.java
  src/main/java/duke/gui/Main.java
  src/main/java/duke/gui/MainWindow.java
  src/main/java/duke/modules/TaskWithMultiplePeriods.java
  src/main/java/duke/modules/TaskWithMultipleWeeklyPeriod.java
  src/main/java/duke/util/ParserWrapper.java
  src/main/java/duke/util/PlannerUi.java
  src/main/java/duke/util/argparse4j/Argparse4jWrapper.java
  src/main/java/duke/util/argparse4j/action/HelpChoices.java
  src/main/java/duke/util/argparse4j/action/Join.java
  src/main/java/duke/util/commons/ModuleTasksList.java
  src/main/resources/images/DaDuke.png
  src/main/resources/images/DaUser.png
  src/main/resources/view/duke.DialogBox.fxml
  src/main/resources/view/duke.MainWindow.fxml
Labels: status.Completed, type.Proposal

#104 Fixed add and remove command bugs
  src/main/java/duke/Duke.java
  src/main/java/duke/command/logic/AddCcaScheduleCommand.java
  src/main/java/duke/command/logic/RemoveCommand.java
  src/main/java/duke/util/argparse4j/Argparse4jWrapper.java
Labels: priority.High, severity.High, type.Fix

#112 [Fix] Bug Fix for ModuleDetailed and Add function
  src/main/java/duke/Duke.java
  src/main/java/planner/command/CapCommand.java
  src/main/java/planner/command/ClearCommand.java
  src/main/java/planner/command/SearchThenAddCommand.java
  src/main/java/planner/exceptions/planner/ModClashesException.java
  src/main/java/planner/modules/data/ModuleInfoDetailed.java
  src/main/java/planner/modules/data/ModuleTask.java
  src/main/java/planner/util/commons/ModuleTasksList.java
Labels: priority.High, severity.High, type.Fix

#113 Resolved merge conflicts from #109
  build.gradle
  docs/screenshots/Architecture.png
  docs/screenshots/CCA.png
  docs/screenshots/Command.png
  docs/screenshots/JsonWrapper.png
  docs/screenshots/Parser.png
  docs/screenshots/PlannerUi.png
  docs/screenshots/Storage.png
  src/main/java/planner/logic/command/ShowCommand.java
  src/main/java/planner/logic/command/SortCommand.java
  src/main/java/planner/logic/modules/module/ModuleTasksList.java
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/ui/cli/PlannerUi.java
Labels: type.Fix, type.Task

#119 [Docs] - Added more detail to JsonWrapper
  build.gradle
  docs/DeveloperGuide.adoc
  docs/images/FutureRequests.png
  docs/images/JsonWrapperSequenceDiag.png
  docs/images/ModuleInfoDetailed.png
Labels: type.Doc

#121 [Feature] - Added support for basic Logger
  .gitignore
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/main/CliLauncher.java
  src/main/java/planner/util/logger/PlannerLogger.java
  src/main/java/planner/util/logger/formatter/LoggerFormatter.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.txt
  text-ui-test/input.txt
  text-ui-test/runtest.bat
Labels: priority.High, status.Ongoing, type.Feature

#122 [Release] - Added preliminary support for coveralls
  .travis.yml
  README.md
  build.gradle
Labels: priority.Medium, status.Ongoing, type.Proposal

#120 [Docs] [Fix] Updated Parser and CCA implementation & Fixed SortCommand parsing
  docs/DeveloperGuide.adoc
  docs/images/ParseCommandSequenceDiagram.png
  src/main/java/planner/logic/parser/Parser.java
Labels: type.Doc

#125 [Feature] Added base support for credential
  src/main/java/planner/util/legacy/reminder/Reminder.java
  src/main/java/planner/util/legacy/reminder/UpcomingTaskReminder.java
Labels: type.Feature

#129 Updated Reminder Command
  src/main/java/planner/logic/command/ReminderCommand.java
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/util/legacy/reminder/OneDayReminder.java
  src/main/java/planner/util/legacy/reminder/OneHourReminder.java
  src/main/java/planner/util/legacy/reminder/ThirtyMinReminder.java
  src/main/java/planner/util/legacy/reminder/TwevleHourReminder.java
Labels: type.Feature
