Repository AY1920S1-CS2113T-F10-1/main, pull requests merged in 2019-11, with the labels that each got.

#193 Fixed ShowCommand for zero indexing
  src/main/java/planner/logic/command/ReminderCommand.java
  src/main/java/planner/logic/command/ShowCommand.java
  src/main/java/planner/util/legacy/reminder/OneDayReminder.java
  src/main/java/planner/util/legacy/reminder/OneHourReminder.java
  src/main/java/planner/util/legacy/reminder/Reminder.java
  src/main/java/planner/util/legacy/reminder/ThirtyMinReminder.java
  src/main/java/planner/util/legacy/reminder/TwevleHourReminder.java
Labels: type.Fix

#192 Fix CapCommand, some bugfixes
  build.gradle
  config/checkstyle/checkstyle.xml
  docs/DeveloperGuide.adoc
  src/main/java/planner/logic/command/CapCommand.java
  src/main/java/planner/logic/command/GradeCommand.java
  src/main/java/planner/logic/command/RemoveCommand.java
  src/main/java/planner/logic/exceptions/planner/ModNoPrerequisiteException.java
  src/main/java/planner/logic/modules/legacy/task/Task.java
  src/main/java/planner/logic/modules/module/ModuleInfoDetailed.java
  src/main/java/planner/logic/modules/module/ModuleTask.java
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/main/CliLauncher.java
  src/main/java/planner/ui/cli/PlannerUi.java
  src/test/java/planner/logic/command/GradeTest.java
Labels: type.Feature

#198 [Test] - Updated test cases
  src/main/java/planner/logic/modules/module/ModuleInfoDetailed.java
  src/main/java/planner/logic/modules/module/ModuleTask.java
  src/main/java/planner/logic/modules/module/ModuleTasksList.java
  src/main/java/planner/util/crawler/JsonWrapper.java
  src/test/java/planner/InputTest.java
  src/test/java/planner/PlannerTest.java
  src/test/java/planner/logic/command/GradeTest.java
  src/test/java/planner/logic/command/ShowTest.java
  src/test/java/planner/logic/modules/module/ModuleInfoDetailedTest.java
Labels: priority.Medium, type.Proposal

#199 Fixed the wrong reminder command
  src/main/java/planner/logic/command/ReminderCommand.java
  src/main/java/planner/ui/cli/PlannerUi.java
Labels: type.Fix

#201 Changed the clear command for standardisation
  src/main/java/planner/logic/command/ClearCommand.java
  src/main/java/planner/logic/parser/Parser.java
  src/test/java/planner/logic/command/ShowCommandTest.java
  test.txt
Labels: type.Feature

#205 Fixed clash check
  src/main/java/planner/credential/user/TaskLists.java
  src/main/java/planner/logic/command/AddCcaScheduleCommand.java
  src/main/java/planner/util/legacy/periods/TimePeriodSpanning.java
  src/main/java/planner/util/legacy/periods/TimePeriodWeekly.java
  test.txt
Labels: type.Fix

#207 Disabled password for ease of testing
  src/main/java/planner/logic/parser/Parser.java
Labels: status.Completed

#206 SortCommand supporting reverse sorts
  .gitignore
  src/main/java/planner/logic/command/SortCommand.java
  src/main/java/planner/logic/modules/module/ModuleInfoDetailed.java
  src/main/java/planner/logic/modules/module/ModuleTask.java
  src/main/java/planner/logic/modules/module/MosuleTaskList.java
  src/main/java/planner/logic/parser/Parser.java
  test.txt
Labels: type.Feature

#212 Updated reminder stop in reminder command
  src/main/java/planner/logic/command/ReminderCommand.java
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/ui/cli/PlannerUi.java
  src/main/java/planner/util/legacy/schedule/ModTimer.java
  src/main/java/planner/util/legacy/schedule/ScheduledTask.java
  src/test/java/planner/logic/command/ShowCommandOneTest.java
  src/test/java/planner/logic/command/ShowCommandTest.java
  test.txt
Labels: type.Feature

#214 Fix for #213 and enabled cca-module cross clash checking
  src/main/java/planner/credential/cryptography/KeyPair.java
  src/main/java/planner/credential/user/TaskLists.java
  src/main/java/planner/credential/user/User.java
  src/main/java/planner/logic/command/AddCcaScheduleCommand.java
  src/main/java/planner/logic/command/ClearCommand.java
  src/main/java/planner/logic/command/SearchThenAddCommand.java
  src/main/java/planner/logic/command/SortCommand.java
  src/main/java/planner/logic/exceptions/legacy/ModCcaScheduleException.java
  src/main/java/planner/logic/exceptions/legacy/ModException.java
  src/main/java/planner/logic/exceptions/legacy/ModScheduleException.java
  src/main/java/planner/logic/exceptions/planner/ModSameModuleException.java
  src/main/java/planner/logic/exceptions/planner/ModTamperedDataException.java
  src/main/java/planner/logic/modules/TaskList.java
  src/main/java/planner/logic/modules/legacy/task/Task.java
  src/main/java/planner/logic/modules/legacy/task/TaskWithMultipleWeeklyPeriod.java
  src/main/java/planner/logic/modules/module/ModuleTasksList.java
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/main/CliLauncher.java
  src/main/java/planner/ui/cli/PlannerUi.java
  src/main/java/planner/util/storage/Storage.java
  src/test/java/planner/logic/parser/ParserTest.java
  test.txt
Labels: severity.High, status.Completed, type.Fix

#216 Added test cases for Show Command
  src/main/java/planner/logic/command/ReminderCommand.java
  src/main/java/planner/logic/command/ShowCommand.java
  src/main/java/planner/ui/cli/PlannerUi.java
  src/test/java/planner/logic/command/ShowCommandOneTest.java
  src/test/java/planner/logic/command/ShowCoreTest.java
  src/test/java/planner/logic/command/ShowGeTest.java
  src/test/java/planner/logic/command/ShowModule.java
  src/test/java/planner/logic/command/ShowUeTest.java
Labels: type.Fix

#215 [Fix] - Update command works as intended
  .gitignore
  .travis.yml
  build.gradle
  gradle.properties
  src/main/java/planner/logic/command/RemoveCommand.java
  src/main/java/planner/logic/command/UpdateModuleCommand.java
  src/main/java/planner/logic/command/UpdateModuleInfo.java
  src/main/java/planner/logic/exceptions/planner/ModUpdateErrorException.java
  src/main/java/planner/logic/modules/cca/Cca.java
  src/main/java/planner/logic/modules/legacy/task/Task.java
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/ui/cli/PlannerUi.java
  src/test/java/planner/logic/command/ShowCommandOneTest.java
  src/test/java/planner/logic/command/ShowCoreTest.java
  src/test/java/planner/logic/command/ShowGeTest.java
  src/test/java/planner/logic/command/ShowModule.java
  src/test/java/planner/logic/command/ShowTest.java
  src/test/java/planner/logic/command/ShowUeTest.java
  src/test/java/planner/logic/command/SortCcaTest.java
  src/test/java/planner/logic/command/SortModuleTest.java
  src/test/java/planner/logic/command/SortTest.java
  src/test/java/planner/logic/command/SortTimeTest.java
  src/test/java/planner/logic/modules/cca/CcaTest.java
  src/test/java/planner/logic/parser/ParserTest.java
  src/test/java/planner/main/DummyTest.java
  src/test/java/planner/main/GradeTest.java
  src/test/java/planner/main/InputTest.java
  src/test/java/planner/main/PlannerTest.java
Labels: severity.High, status.Completed, type.Fix

#220 Added ClearCommand Test and some bug fixes, (finally) got GUI to work properly
  src/main/java/planner/logic/command/CapCommand.java
  src/main/java/planner/logic/command/ClearCommand.java
  src/main/java/planner/logic/command/ReminderCommand.java
  src/main/java/planner/logic/command/ShowCommand.java
  src/main/java/planner/logic/parser/Parser.java
  src/main/java/planner/main/CliLauncher.java
  src/main/java/planner/ui/cli/PlannerUi.java
  src/main/java/planner/ui/gui/DialogBox.java
  src/main/java/planner/ui/gui/Main.java
  src/main/java/planner/ui/gui/MainWindow.java
  src/main/java/planner/util/legacy/schedule/ScheduledTask.java
  src/main/resources/view/DialogBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/planner/logic/command/ClearCommandTest.java
  src/test/java/planner/logic/command/CommandTestFramework.java
  src/test/java/planner/main/PlannerTest.java
Labels: type.Fix, type.Task

#219 Added testing for storage and exceptions
  src/main/java/planner/logic/command/ModuleComInterface.java
  src/main/java/planner/logic/exceptions/legacy/ModEmptyListException.java
  src/main/java/planner/logic/exceptions/legacy/ModMultipleValuesForSameArgumentException.java
  src/main/java/planner/logic/modules/module/ModuleInfoSummary.java
  src/main/java/planner/logic/modules/module/ModuleTask.java
  src/main/java/planner/ui/cli/PlannerUi.java
  src/main/java/planner/util/crawler/JsonWrapper.java
  src/main/java/planner/util/storage/Storage.java
  src/test/java/planner/logic/command/ShowCommandOneTest.java
  src/test/java/planner/logic/command/ShowCoreTest.java
  src/test/java/planner/logic/command/ShowGeTest.java
  src/test/java/planner/logic/command/ShowModule.java
  src/test/java/planner/logic/command/ShowTest.java
  src/test/java/planner/logic/command/ShowUeTest.java
  src/test/java/planner/logic/command/SortCcaTest.java
  src/test/java/planner/logic/command/SortModuleTest.java
  src/test/java/planner/logic/command/SortTest.java
  src/test/java/planner/logic/command/SortTimeTest.java
  src/test/java/planner/logic/exceptions/legacy/LegacyExceptionTest.java
  src/test/java/planner/logic/exceptions/legacy/ModTestException.java
  src/test/java/planner/logic/exceptions/planner/PlannerExceptionTest.java
  src/test/java/planner/main/GradeTest.java
  src/test/java/planner/main/InputTest.java
  src/test/java/planner/ui/cli/PlannerUiTest.java
  src/test/java/planner/util/PlannerParserTest.java
  src/test/java/planner/util/datetime/NattyTesting.java
  src/test/java/planner/util/storage/StorageTest.java
Labels: type.Task

#224 Fix for CCA not clashing
  src/main/java/planner/util/legacy/periods/TimePeriodWeekly.java
  test.txt
Labels: priority.High, type.Fix

#226 Changes to UG and some module testing classes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/architecture.puml
  docs/images/test.puml
  src/main/java/planner/logic/modules/module/ModuleTask.java
  src/test/java/planner/logic/modules/module/ModuleTaskListTest.java
  src/test/java/planner/logic/modules/module/ModuleTaskTest.java
  test.txt
Labels: priority.High, status.Ongoing, type.Task

#227 Bug fix for carriage return in windows
  build.gradle
  src/main/java/planner/ui/cli/PlannerUi.java
Labels: type.Fix
